# Site settings
title: Enterprise Software Patterns
email: john.d.ament@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog around java, EE stacks
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://john.ament.ws" # the base hostname & protocol for your site
twitter_username: johnament
github_username:  johnament

# Build settings
markdown: kramdown
